apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-dispatcher
  namespace: notification-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-dispatcher
  template:
    metadata:
      labels:
        app: notification-dispatcher
    spec:
      containers:
      - name: notification-dispatcher
        image: notification-dispatcher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: EUREKA_SERVER_URL
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: DATABASE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: DATABASE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: DATABASE_PASSWORD
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-dispatcher
  namespace: notification-system
spec:
  selector:
    app: notification-dispatcher
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP