apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-producer
  namespace: notification-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-producer
  template:
    metadata:
      labels:
        app: notification-producer
    spec:
      containers:
      - name: notification-producer
        image: notification-producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: EUREKA_SERVER_URL
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-producer
  namespace: notification-system
spec:
  selector:
    app: notification-producer
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP