version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: notification-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - 3307:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - notification-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
      interval: 10s
      start_period: 30s

  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - notification-network
    depends_on:
      mariadb:
        condition: service_started
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  notification-producer:
    build:
      context: ../microservice-notification-producer
      dockerfile: Dockerfile
    container_name: notification-producer
    restart: always
    ports:
      - "8081:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - notification-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  notification-dispatcher:
    build:
      context: ../microservice-notification-dispatcher
      dockerfile: Dockerfile
    container_name: notification-dispatcher
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      mariadb:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - notification-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

volumes:
  mariadb_data:

networks:
  notification-network:
    driver: bridge